### ISSUE TITLE
Homebrew recipe fails with sudo error (MacOS Sierra)

### ISSUE THREAD

**Issue by mag** [pivotal-sprout/sprout-wrap#98] opened 2016-10-16 23:42 UTC
Hi guys!

I have a fresh install of Sierra here and tried to run sprout-wrap. First problem I ran into was that homebrew did not install (see below). I hand-installed homebrew and got past this problem (but ran into another error - will post that one separately)

```
  * execute[install homebrew] action run[2016-10-16T16:27:46-07:00] INFO: Processing execute[install homebrew] action run (homebrew::default line 39)

    [execute] ==> This script will install:
              /usr/local/bin/brew
              /usr/local/share/doc/homebrew
              /usr/local/share/man/man1/brew.1
              /usr/local/share/zsh/site-functions/_brew
              /usr/local/etc/bash_completion.d/brew
              /usr/local/Homebrew
              ==> The following new directories will be created:
              /usr/local/Cellar
              /usr/local/Homebrew
              /usr/local/Frameworks
              /usr/local/bin
              /usr/local/etc
              /usr/local/include
              /usr/local/lib
              /usr/local/opt
              /usr/local/sbin
              /usr/local/share
              /usr/local/share/zsh
              /usr/local/share/zsh/site-functions
              /usr/local/var
              ==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
              sudo: no tty present and no askpass program specified
              Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var

    ================================================================================
    Error executing action `run` on resource 'execute[install homebrew]'
    ================================================================================
```

**Comment by ClayShentrup** [comment] 2017-01-17 05:44
I get the exact same problem.

**Comment by aramprice** [comment] 2017-01-17 17:34
I haven't seen this but I haven't done a fresh install on a recent version of sierra. This issue from the homebrew cookbook might be relevant: https://github.com/chef-cookbooks/homebrew/issues/111

**Comment by aramprice** [comment] 2017-01-17 17:40
FWIW there has been some discussion internally about dropping sprout in favor of [Brewfile](https://github.com/Homebrew/homebrew-bundle) plus some sort of [dotfiles](https://dotfiles.github.io) tooling. Some open questions are bash-it installation/integration and overall bootstrapping/entry-point.

Mostly this has been driven by the fact that macOS ships with an EOL'd ruby which gems are [dropping  supporting](https://github.com/pivotal-sprout/sprout-chruby/blob/master/Gemfile#L12-L20) for.

**Comment by ClayShentrup** [comment] 2017-01-17 18:02
@aramprice Good to know! Thanks. Is there any way I can stay posted of any updates on this decision?

**Comment by aramprice** [comment] 2017-01-17 20:25
@ClayShentrup I don't think these are anywhere I can link to. I opened https://github.com/pivotal-sprout/sprout-wrap/issues/99 as a place to kick around ideas in a public forum.

**Comment by trinitronx** [comment] 2017-02-07 02:24
This looks similar to [`chef-cookbooks/homebrew#105`][1].  I've just pushed a recipe for [working around this issue here][2].  The problem is that homebrew wants to run certain commands with `sudo` and `sudo -E` with newer versions, but the default OSX `/etc/sudoers` file does not allow this.

The fix is to configure `sudoers` to [allow `NOPASSWD:SETENV` for those commands][3].

Place the recipe just before `homebrew` recipes in your `run_list`.  Note that if somehow your user or hostname is not detected properly by the cookbook, it may result in a `/etc/sudoers.d/homebrew_chef` config file with invalid syntax.  This may cause you to get locked out of using `sudo`, because Chef has bypassed `visudo` and edited the file directly.  I haven't had time to implement [Validation + `rewind` support like `chef-cookbooks/sudo`][4], so use at your own risk.  If you need to recover after a botched `sudoers` file edit (you do have "Admin" set on your account still right?), [this blog post should help][5].

[1]: https://github.com/chef-cookbooks/homebrew/issues/105
[2]: https://github.com/trinitronx/lyraphase_workstation/blob/master/recipes/homebrew_sudoers.rb
[3]: https://github.com/trinitronx/lyraphase_workstation/blob/master/templates/default/sudoers.d/homebrew_chef.erb
[4]: https://github.com/chef-cookbooks/sudo/blob/master/providers/default.rb#L40-L60
[5]: http://astrails.com/blog/2009/09/29/how-to-fix-a-hosed-etc-sudoers-file-on-mac-osx

**Comment by ClayShentrup** [comment] 2017-03-20 20:07
@aramprice Has there been any thought on this? Is Pivotal actively using Sprout these days?

**Comment by aramprice** [comment] 2017-03-20 21:56
@ClayShentrup there is little active maintenance. Some teams are still using sprout but a growing number are not. The best place to further the discussion is likely https://github.com/pivotal-sprout/sprout-wrap/issues/99

**Comment by TV4Fun** [comment] 2017-05-25 23:23
This is related to https://github.com/caskroom/homebrew-cask/issues/32954. You can work around this by setting SUDO_ASKPASS before running Homebrew.

**Comment by aramprice** [comment] 2024-07-27 00:39
Going to archive this repo, closing.

**Closed by aramprice** 2024-07-27 00:39 UTC
